//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public string CategoryName { get; set; }
        public int CategoryID { get; set; }
        public System.TimeSpan Duration { get; set; }
        public string MovieLink { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
